name: 'vj-pr-comments'
description: 'Add PR Changes as comment'
inputs:
  owner:  # owner of the repo
    description: 'The owner of the repository (user of org)'
    required: true
  repo:
    description: 'The repositiry name'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use access the Github APIs'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
